package com.example.demo.mybatis;

import com.alibaba.fastjson.JSON;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class MobileRefundOrderDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_refund_order.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_refund_order.trade_serial_no
     *
     * @mbg.generated
     */
    private String tradeSerialNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_refund_order.out_refund_no
     *
     * @mbg.generated
     */
    private String outRefundNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_refund_order.out_trade_no
     *
     * @mbg.generated
     */
    private String outTradeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_refund_order.refund_money
     *
     * @mbg.generated
     */
    private BigDecimal refundMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_refund_order.trade_money
     *
     * @mbg.generated
     */
    private BigDecimal tradeMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_refund_order.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_refund_order.subject
     *
     * @mbg.generated
     */
    private String subject;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_refund_order.id
     *
     * @return the value of mobile_refund_order.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_refund_order.id
     *
     * @param id the value for mobile_refund_order.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_refund_order.trade_serial_no
     *
     * @return the value of mobile_refund_order.trade_serial_no
     *
     * @mbg.generated
     */
    public String getTradeSerialNo() {
        return tradeSerialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_refund_order.trade_serial_no
     *
     * @param tradeSerialNo the value for mobile_refund_order.trade_serial_no
     *
     * @mbg.generated
     */
    public void setTradeSerialNo(String tradeSerialNo) {
        this.tradeSerialNo = tradeSerialNo == null ? null : tradeSerialNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_refund_order.out_refund_no
     *
     * @return the value of mobile_refund_order.out_refund_no
     *
     * @mbg.generated
     */
    public String getOutRefundNo() {
        return outRefundNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_refund_order.out_refund_no
     *
     * @param outRefundNo the value for mobile_refund_order.out_refund_no
     *
     * @mbg.generated
     */
    public void setOutRefundNo(String outRefundNo) {
        this.outRefundNo = outRefundNo == null ? null : outRefundNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_refund_order.out_trade_no
     *
     * @return the value of mobile_refund_order.out_trade_no
     *
     * @mbg.generated
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_refund_order.out_trade_no
     *
     * @param outTradeNo the value for mobile_refund_order.out_trade_no
     *
     * @mbg.generated
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo == null ? null : outTradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_refund_order.refund_money
     *
     * @return the value of mobile_refund_order.refund_money
     *
     * @mbg.generated
     */
    public BigDecimal getRefundMoney() {
        return refundMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_refund_order.refund_money
     *
     * @param refundMoney the value for mobile_refund_order.refund_money
     *
     * @mbg.generated
     */
    public void setRefundMoney(BigDecimal refundMoney) {
        this.refundMoney = refundMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_refund_order.trade_money
     *
     * @return the value of mobile_refund_order.trade_money
     *
     * @mbg.generated
     */
    public BigDecimal getTradeMoney() {
        return tradeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_refund_order.trade_money
     *
     * @param tradeMoney the value for mobile_refund_order.trade_money
     *
     * @mbg.generated
     */
    public void setTradeMoney(BigDecimal tradeMoney) {
        this.tradeMoney = tradeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_refund_order.user_id
     *
     * @return the value of mobile_refund_order.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_refund_order.user_id
     *
     * @param userId the value for mobile_refund_order.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_refund_order.subject
     *
     * @return the value of mobile_refund_order.subject
     *
     * @mbg.generated
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_refund_order.subject
     *
     * @param subject the value for mobile_refund_order.subject
     *
     * @mbg.generated
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    public static void main(String[] args) {
        List<MobileRefundOrderDO> list = new ArrayList<>();
        MobileRefundOrderDO mobileRefundOrderDO = new MobileRefundOrderDO();
        mobileRefundOrderDO.setId(1);
        list.add(mobileRefundOrderDO);
        System.out.println("JSON.toJSON(mobileRefundOrderDO) = " + JSON.toJSON(list));
        System.out.println("JSON.toJSON(mobileRefundOrderDO) = " + JSON.toJSONString(list));
    }
}