package com.example.demo.mybatis;

import java.math.BigDecimal;
import java.util.Date;

public class MobileOrderPaymentEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile-order-payment.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile-order-payment.merchant_acct_id
     *
     * @mbg.generated
     */
    private String merchantAcctId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile-order-payment.payer_name
     *
     * @mbg.generated
     */
    private String payerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile-order-payment.payer_contact_type
     *
     * @mbg.generated
     */
    private Integer payerContactType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile-order-payment.payer_contact
     *
     * @mbg.generated
     */
    private String payerContact;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile-order-payment.payer_id_type
     *
     * @mbg.generated
     */
    private String payerIdType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile-order-payment.payer_id
     *
     * @mbg.generated
     */
    private String payerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile-order-payment.payer_ip
     *
     * @mbg.generated
     */
    private String payerIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile-order-payment.order_id
     *
     * @mbg.generated
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile-order-payment.order_amount
     *
     * @mbg.generated
     */
    private BigDecimal orderAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile-order-payment.order_time
     *
     * @mbg.generated
     */
    private Date orderTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile-order-payment.order_timestamp
     *
     * @mbg.generated
     */
    private Date orderTimestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile-order-payment.product_name
     *
     * @mbg.generated
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile-order-payment.product_num
     *
     * @mbg.generated
     */
    private Integer productNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile-order-payment.product_id
     *
     * @mbg.generated
     */
    private String productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile-order-payment.ext1
     *
     * @mbg.generated
     */
    private String ext1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile-order-payment.ext2
     *
     * @mbg.generated
     */
    private String ext2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile-order-payment.pay_type
     *
     * @mbg.generated
     */
    private String payType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile-order-payment.period
     *
     * @mbg.generated
     */
    private Integer period;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile-order-payment.bank_id
     *
     * @mbg.generated
     */
    private String bankId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile-order-payment.card_issuer
     *
     * @mbg.generated
     */
    private String cardIssuer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile-order-payment.card_num
     *
     * @mbg.generated
     */
    private String cardNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile-order-payment.redo_flag
     *
     * @mbg.generated
     */
    private Integer redoFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile-order-payment.submit_type
     *
     * @mbg.generated
     */
    private String submitType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile-order-payment.order_time_out
     *
     * @mbg.generated
     */
    private Integer orderTimeOut;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile-order-payment.refer_data_type
     *
     * @mbg.generated
     */
    private String referDataType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile-order-payment.bill99_order_no
     *
     * @mbg.generated
     */
    private String bill99OrderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile-order-payment.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile-order-payment.pay_time
     *
     * @mbg.generated
     */
    private Date payTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile-order-payment.product_desc
     *
     * @mbg.generated
     */
    private String productDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile-order-payment.aggregate_pay
     *
     * @mbg.generated
     */
    private String aggregatePay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile-order-payment.ext_data_type
     *
     * @mbg.generated
     */
    private String extDataType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile-order-payment.ext_data_content
     *
     * @mbg.generated
     */
    private String extDataContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile-order-payment.sign_msg
     *
     * @mbg.generated
     */
    private String signMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile-order-payment.refer_data
     *
     * @mbg.generated
     */
    private String referData;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile-order-payment.id
     *
     * @return the value of mobile-order-payment.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile-order-payment.id
     *
     * @param id the value for mobile-order-payment.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile-order-payment.merchant_acct_id
     *
     * @return the value of mobile-order-payment.merchant_acct_id
     *
     * @mbg.generated
     */
    public String getMerchantAcctId() {
        return merchantAcctId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile-order-payment.merchant_acct_id
     *
     * @param merchantAcctId the value for mobile-order-payment.merchant_acct_id
     *
     * @mbg.generated
     */
    public void setMerchantAcctId(String merchantAcctId) {
        this.merchantAcctId = merchantAcctId == null ? null : merchantAcctId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile-order-payment.payer_name
     *
     * @return the value of mobile-order-payment.payer_name
     *
     * @mbg.generated
     */
    public String getPayerName() {
        return payerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile-order-payment.payer_name
     *
     * @param payerName the value for mobile-order-payment.payer_name
     *
     * @mbg.generated
     */
    public void setPayerName(String payerName) {
        this.payerName = payerName == null ? null : payerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile-order-payment.payer_contact_type
     *
     * @return the value of mobile-order-payment.payer_contact_type
     *
     * @mbg.generated
     */
    public Integer getPayerContactType() {
        return payerContactType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile-order-payment.payer_contact_type
     *
     * @param payerContactType the value for mobile-order-payment.payer_contact_type
     *
     * @mbg.generated
     */
    public void setPayerContactType(Integer payerContactType) {
        this.payerContactType = payerContactType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile-order-payment.payer_contact
     *
     * @return the value of mobile-order-payment.payer_contact
     *
     * @mbg.generated
     */
    public String getPayerContact() {
        return payerContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile-order-payment.payer_contact
     *
     * @param payerContact the value for mobile-order-payment.payer_contact
     *
     * @mbg.generated
     */
    public void setPayerContact(String payerContact) {
        this.payerContact = payerContact == null ? null : payerContact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile-order-payment.payer_id_type
     *
     * @return the value of mobile-order-payment.payer_id_type
     *
     * @mbg.generated
     */
    public String getPayerIdType() {
        return payerIdType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile-order-payment.payer_id_type
     *
     * @param payerIdType the value for mobile-order-payment.payer_id_type
     *
     * @mbg.generated
     */
    public void setPayerIdType(String payerIdType) {
        this.payerIdType = payerIdType == null ? null : payerIdType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile-order-payment.payer_id
     *
     * @return the value of mobile-order-payment.payer_id
     *
     * @mbg.generated
     */
    public String getPayerId() {
        return payerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile-order-payment.payer_id
     *
     * @param payerId the value for mobile-order-payment.payer_id
     *
     * @mbg.generated
     */
    public void setPayerId(String payerId) {
        this.payerId = payerId == null ? null : payerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile-order-payment.payer_ip
     *
     * @return the value of mobile-order-payment.payer_ip
     *
     * @mbg.generated
     */
    public String getPayerIp() {
        return payerIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile-order-payment.payer_ip
     *
     * @param payerIp the value for mobile-order-payment.payer_ip
     *
     * @mbg.generated
     */
    public void setPayerIp(String payerIp) {
        this.payerIp = payerIp == null ? null : payerIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile-order-payment.order_id
     *
     * @return the value of mobile-order-payment.order_id
     *
     * @mbg.generated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile-order-payment.order_id
     *
     * @param orderId the value for mobile-order-payment.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile-order-payment.order_amount
     *
     * @return the value of mobile-order-payment.order_amount
     *
     * @mbg.generated
     */
    public BigDecimal getOrderAmount() {
        return orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile-order-payment.order_amount
     *
     * @param orderAmount the value for mobile-order-payment.order_amount
     *
     * @mbg.generated
     */
    public void setOrderAmount(BigDecimal orderAmount) {
        this.orderAmount = orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile-order-payment.order_time
     *
     * @return the value of mobile-order-payment.order_time
     *
     * @mbg.generated
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile-order-payment.order_time
     *
     * @param orderTime the value for mobile-order-payment.order_time
     *
     * @mbg.generated
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile-order-payment.order_timestamp
     *
     * @return the value of mobile-order-payment.order_timestamp
     *
     * @mbg.generated
     */
    public Date getOrderTimestamp() {
        return orderTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile-order-payment.order_timestamp
     *
     * @param orderTimestamp the value for mobile-order-payment.order_timestamp
     *
     * @mbg.generated
     */
    public void setOrderTimestamp(Date orderTimestamp) {
        this.orderTimestamp = orderTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile-order-payment.product_name
     *
     * @return the value of mobile-order-payment.product_name
     *
     * @mbg.generated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile-order-payment.product_name
     *
     * @param productName the value for mobile-order-payment.product_name
     *
     * @mbg.generated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile-order-payment.product_num
     *
     * @return the value of mobile-order-payment.product_num
     *
     * @mbg.generated
     */
    public Integer getProductNum() {
        return productNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile-order-payment.product_num
     *
     * @param productNum the value for mobile-order-payment.product_num
     *
     * @mbg.generated
     */
    public void setProductNum(Integer productNum) {
        this.productNum = productNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile-order-payment.product_id
     *
     * @return the value of mobile-order-payment.product_id
     *
     * @mbg.generated
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile-order-payment.product_id
     *
     * @param productId the value for mobile-order-payment.product_id
     *
     * @mbg.generated
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile-order-payment.ext1
     *
     * @return the value of mobile-order-payment.ext1
     *
     * @mbg.generated
     */
    public String getExt1() {
        return ext1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile-order-payment.ext1
     *
     * @param ext1 the value for mobile-order-payment.ext1
     *
     * @mbg.generated
     */
    public void setExt1(String ext1) {
        this.ext1 = ext1 == null ? null : ext1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile-order-payment.ext2
     *
     * @return the value of mobile-order-payment.ext2
     *
     * @mbg.generated
     */
    public String getExt2() {
        return ext2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile-order-payment.ext2
     *
     * @param ext2 the value for mobile-order-payment.ext2
     *
     * @mbg.generated
     */
    public void setExt2(String ext2) {
        this.ext2 = ext2 == null ? null : ext2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile-order-payment.pay_type
     *
     * @return the value of mobile-order-payment.pay_type
     *
     * @mbg.generated
     */
    public String getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile-order-payment.pay_type
     *
     * @param payType the value for mobile-order-payment.pay_type
     *
     * @mbg.generated
     */
    public void setPayType(String payType) {
        this.payType = payType == null ? null : payType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile-order-payment.period
     *
     * @return the value of mobile-order-payment.period
     *
     * @mbg.generated
     */
    public Integer getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile-order-payment.period
     *
     * @param period the value for mobile-order-payment.period
     *
     * @mbg.generated
     */
    public void setPeriod(Integer period) {
        this.period = period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile-order-payment.bank_id
     *
     * @return the value of mobile-order-payment.bank_id
     *
     * @mbg.generated
     */
    public String getBankId() {
        return bankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile-order-payment.bank_id
     *
     * @param bankId the value for mobile-order-payment.bank_id
     *
     * @mbg.generated
     */
    public void setBankId(String bankId) {
        this.bankId = bankId == null ? null : bankId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile-order-payment.card_issuer
     *
     * @return the value of mobile-order-payment.card_issuer
     *
     * @mbg.generated
     */
    public String getCardIssuer() {
        return cardIssuer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile-order-payment.card_issuer
     *
     * @param cardIssuer the value for mobile-order-payment.card_issuer
     *
     * @mbg.generated
     */
    public void setCardIssuer(String cardIssuer) {
        this.cardIssuer = cardIssuer == null ? null : cardIssuer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile-order-payment.card_num
     *
     * @return the value of mobile-order-payment.card_num
     *
     * @mbg.generated
     */
    public String getCardNum() {
        return cardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile-order-payment.card_num
     *
     * @param cardNum the value for mobile-order-payment.card_num
     *
     * @mbg.generated
     */
    public void setCardNum(String cardNum) {
        this.cardNum = cardNum == null ? null : cardNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile-order-payment.redo_flag
     *
     * @return the value of mobile-order-payment.redo_flag
     *
     * @mbg.generated
     */
    public Integer getRedoFlag() {
        return redoFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile-order-payment.redo_flag
     *
     * @param redoFlag the value for mobile-order-payment.redo_flag
     *
     * @mbg.generated
     */
    public void setRedoFlag(Integer redoFlag) {
        this.redoFlag = redoFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile-order-payment.submit_type
     *
     * @return the value of mobile-order-payment.submit_type
     *
     * @mbg.generated
     */
    public String getSubmitType() {
        return submitType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile-order-payment.submit_type
     *
     * @param submitType the value for mobile-order-payment.submit_type
     *
     * @mbg.generated
     */
    public void setSubmitType(String submitType) {
        this.submitType = submitType == null ? null : submitType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile-order-payment.order_time_out
     *
     * @return the value of mobile-order-payment.order_time_out
     *
     * @mbg.generated
     */
    public Integer getOrderTimeOut() {
        return orderTimeOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile-order-payment.order_time_out
     *
     * @param orderTimeOut the value for mobile-order-payment.order_time_out
     *
     * @mbg.generated
     */
    public void setOrderTimeOut(Integer orderTimeOut) {
        this.orderTimeOut = orderTimeOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile-order-payment.refer_data_type
     *
     * @return the value of mobile-order-payment.refer_data_type
     *
     * @mbg.generated
     */
    public String getReferDataType() {
        return referDataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile-order-payment.refer_data_type
     *
     * @param referDataType the value for mobile-order-payment.refer_data_type
     *
     * @mbg.generated
     */
    public void setReferDataType(String referDataType) {
        this.referDataType = referDataType == null ? null : referDataType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile-order-payment.bill99_order_no
     *
     * @return the value of mobile-order-payment.bill99_order_no
     *
     * @mbg.generated
     */
    public String getBill99OrderNo() {
        return bill99OrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile-order-payment.bill99_order_no
     *
     * @param bill99OrderNo the value for mobile-order-payment.bill99_order_no
     *
     * @mbg.generated
     */
    public void setBill99OrderNo(String bill99OrderNo) {
        this.bill99OrderNo = bill99OrderNo == null ? null : bill99OrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile-order-payment.status
     *
     * @return the value of mobile-order-payment.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile-order-payment.status
     *
     * @param status the value for mobile-order-payment.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile-order-payment.pay_time
     *
     * @return the value of mobile-order-payment.pay_time
     *
     * @mbg.generated
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile-order-payment.pay_time
     *
     * @param payTime the value for mobile-order-payment.pay_time
     *
     * @mbg.generated
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile-order-payment.product_desc
     *
     * @return the value of mobile-order-payment.product_desc
     *
     * @mbg.generated
     */
    public String getProductDesc() {
        return productDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile-order-payment.product_desc
     *
     * @param productDesc the value for mobile-order-payment.product_desc
     *
     * @mbg.generated
     */
    public void setProductDesc(String productDesc) {
        this.productDesc = productDesc == null ? null : productDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile-order-payment.aggregate_pay
     *
     * @return the value of mobile-order-payment.aggregate_pay
     *
     * @mbg.generated
     */
    public String getAggregatePay() {
        return aggregatePay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile-order-payment.aggregate_pay
     *
     * @param aggregatePay the value for mobile-order-payment.aggregate_pay
     *
     * @mbg.generated
     */
    public void setAggregatePay(String aggregatePay) {
        this.aggregatePay = aggregatePay == null ? null : aggregatePay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile-order-payment.ext_data_type
     *
     * @return the value of mobile-order-payment.ext_data_type
     *
     * @mbg.generated
     */
    public String getExtDataType() {
        return extDataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile-order-payment.ext_data_type
     *
     * @param extDataType the value for mobile-order-payment.ext_data_type
     *
     * @mbg.generated
     */
    public void setExtDataType(String extDataType) {
        this.extDataType = extDataType == null ? null : extDataType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile-order-payment.ext_data_content
     *
     * @return the value of mobile-order-payment.ext_data_content
     *
     * @mbg.generated
     */
    public String getExtDataContent() {
        return extDataContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile-order-payment.ext_data_content
     *
     * @param extDataContent the value for mobile-order-payment.ext_data_content
     *
     * @mbg.generated
     */
    public void setExtDataContent(String extDataContent) {
        this.extDataContent = extDataContent == null ? null : extDataContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile-order-payment.sign_msg
     *
     * @return the value of mobile-order-payment.sign_msg
     *
     * @mbg.generated
     */
    public String getSignMsg() {
        return signMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile-order-payment.sign_msg
     *
     * @param signMsg the value for mobile-order-payment.sign_msg
     *
     * @mbg.generated
     */
    public void setSignMsg(String signMsg) {
        this.signMsg = signMsg == null ? null : signMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile-order-payment.refer_data
     *
     * @return the value of mobile-order-payment.refer_data
     *
     * @mbg.generated
     */
    public String getReferData() {
        return referData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile-order-payment.refer_data
     *
     * @param referData the value for mobile-order-payment.refer_data
     *
     * @mbg.generated
     */
    public void setReferData(String referData) {
        this.referData = referData == null ? null : referData.trim();
    }
}