package com.example.demo.mybatis;

import java.util.Date;

public class NotifyInfoLogDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notify_info_log.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notify_info_log.retry_info
     *
     * @mbg.generated
     */
    private String retryInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notify_info_log.is_deleted
     *
     * @mbg.generated
     */
    private String isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notify_info_log.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notify_info_log.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notify_info_log.id
     *
     * @return the value of t_notify_info_log.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notify_info_log.id
     *
     * @param id the value for t_notify_info_log.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notify_info_log.retry_info
     *
     * @return the value of t_notify_info_log.retry_info
     *
     * @mbg.generated
     */
    public String getRetryInfo() {
        return retryInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notify_info_log.retry_info
     *
     * @param retryInfo the value for t_notify_info_log.retry_info
     *
     * @mbg.generated
     */
    public void setRetryInfo(String retryInfo) {
        this.retryInfo = retryInfo == null ? null : retryInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notify_info_log.is_deleted
     *
     * @return the value of t_notify_info_log.is_deleted
     *
     * @mbg.generated
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notify_info_log.is_deleted
     *
     * @param isDeleted the value for t_notify_info_log.is_deleted
     *
     * @mbg.generated
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notify_info_log.create_time
     *
     * @return the value of t_notify_info_log.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notify_info_log.create_time
     *
     * @param createTime the value for t_notify_info_log.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notify_info_log.update_time
     *
     * @return the value of t_notify_info_log.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notify_info_log.update_time
     *
     * @param updateTime the value for t_notify_info_log.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}