package com.example.demo.mybatis.dao;

import com.example.demo.mybatis.BusinessEnums;

import java.util.List;

public interface BusinessEnumsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_enums
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_enums
     *
     * @mbg.generated
     */
    int insert(BusinessEnums record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_enums
     *
     * @mbg.generated
     */
    int insertSelective(BusinessEnums record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_enums
     *
     * @mbg.generated
     */
    BusinessEnums selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_enums
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BusinessEnums record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_enums
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BusinessEnums record);

    List<BusinessEnums> getListBusinessEnums();

    BusinessEnums selectByTypeAndCode(BusinessEnums  businessEnums);

}