package com.example.demo.mybatis.dao;

import com.example.demo.mybatis.MobileOrderPaymentEntity;

public interface MobileOrderPaymentEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile-order-payment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile-order-payment
     *
     * @mbg.generated
     */
    int insert(MobileOrderPaymentEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile-order-payment
     *
     * @mbg.generated
     */
    int insertSelective(MobileOrderPaymentEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile-order-payment
     *
     * @mbg.generated
     */
    MobileOrderPaymentEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile-order-payment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MobileOrderPaymentEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile-order-payment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(MobileOrderPaymentEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile-order-payment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MobileOrderPaymentEntity record);
}