package com.example.demo.mybatis.dao;

import com.example.demo.mybatis.MobileRefundOrderDO;

public interface MobileRefundOrderDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_refund_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_refund_order
     *
     * @mbg.generated
     */
    int insert(MobileRefundOrderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_refund_order
     *
     * @mbg.generated
     */
    int insertSelective(MobileRefundOrderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_refund_order
     *
     * @mbg.generated
     */
    MobileRefundOrderDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_refund_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MobileRefundOrderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_refund_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MobileRefundOrderDO record);
}