//package com.example.demo.mybatis.dao;
//
//public interface MobileRefundDOMapper {
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table mobile_refund_order
//     *
//     * @mbg.generated
//     */
//    int deleteByPrimaryKey(Integer id);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table mobile_refund_order
//     *
//     * @mbg.generated
//     */
//    int insert(MobileRefundDO record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table mobile_refund_order
//     *
//     * @mbg.generated
//     */
//    int insertSelective(MobileRefundDO record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table mobile_refund_order
//     *
//     * @mbg.generated
//     */
//    MobileRefundDO selectByPrimaryKey(Integer id);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table mobile_refund_order
//     *
//     * @mbg.generated
//     */
//    int updateByPrimaryKeySelective(MobileRefundDO record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table mobile_refund_order
//     *
//     * @mbg.generated
//     */
//    int updateByPrimaryKey(MobileRefundDO record);
//}