package com.example.demo.mybatis.dao;

import com.example.demo.mybatis.NotifyInfoLogDO;

public interface NotifyInfoLogDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notify_info_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notify_info_log
     *
     * @mbg.generated
     */
    int insert(NotifyInfoLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notify_info_log
     *
     * @mbg.generated
     */
    int insertSelective(NotifyInfoLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notify_info_log
     *
     * @mbg.generated
     */
    NotifyInfoLogDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notify_info_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(NotifyInfoLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notify_info_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(NotifyInfoLogDO record);
}