package com.example.demo.mybatis.dao;

import com.example.demo.mybatis.PaymentBill99;

public interface PaymentBill99Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment_bill99
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment_bill99
     *
     * @mbg.generated
     */
    int insert(PaymentBill99 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment_bill99
     *
     * @mbg.generated
     */
    int insertSelective(PaymentBill99 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment_bill99
     *
     * @mbg.generated
     */
    PaymentBill99 selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment_bill99
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PaymentBill99 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment_bill99
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(PaymentBill99 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment_bill99
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PaymentBill99 record);
}